# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Started creating infra in Azure for VM
  displayName: 'STEP 1'

- script: |
    echo finished infrastructure creation
  displayName: 'STEP 2'
