# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/add-template-to-azure-pipelines

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

 
steps:
- bash: |
    MAJOR_RUN=$(echo $BUILD_BUILDNUMBER | cut -d '.' -f1)
    echo "This is the major run number: $MAJOR_RUN"
    echo "##vso[task.setvariable variable=major]$MAJOR_RUN"

    MINOR_RUN=$(echo $BUILD_BUILDNUMBER | cut -d '.' -f2)
    echo "This is the minor run number: $MINOR_RUN"
    echo "##vso[task.setvariable variable=minor]$MINOR_RUN"
    
- script:  echo "RDS Server Creation Started New Account"
  displayName: 'Starter Act'

- task: CopyFiles@2
  displayName: 'Started Copying the files'
  inputs:
    SourceFolder: 'templates'
    Contents: '**'
    TargetFolder: 'Nupkg-Files'
- task: CopyFiles@2
  displayName: 'Started Copying the files'
  inputs:
    SourceFolder: 'templatesVM'
    Contents: '**'
    TargetFolder: 'Nupkg-Files'
- task: OctopusPack@4
  displayName: 'Start Packing Files for Octopus'
  inputs:
    PackageId: 'testpackage'
    PackageFormat: 'NuPkg'
    PackageVersion: '1234'
#    SourcePath: 'Nupkg-Files'
    SourcePath: '.'
    OutputPath: '$(Build.ArtifactStagingDirectory)'

#- task: OctopusPack

#- task: AzurePowerShell@5
#  inputs:
#    azureSubscription: 'Pexabo'
#    ScriptType: 'FilePath'
    
#    ScriptPath: './Deploy-AzTemplate.ps1'
#    ScriptArguments: -Location 'uksouth' -ResourceGroupName RDS$(minor) -TemplateFile templates\mainTemplate.json -ArtifactStagingDirectory 'templates'
#    azurePowerShellVersion: 'LatestVersion'

- script:  echo "RDS Server Creation Ended"
  displayName: 'Ending Scene'
