# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/add-template-to-azure-pipelines

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script:  echo "RDS Server Creation Started New Account"
  displayName: 'STEP 1'

- script:  echo "RDS Server Creation Ended"
  displayName: 'STEP 2'
